imports:
  # Add the Decap CMS module below, if it has not already been added:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-decap-cms

mounts:
- source: 'content'
  target: 'content'
- source: 'static'
  target: 'static'
- source: 'layouts'
  target: 'layouts'
- source: 'data'
  target: 'data'
- source: 'assets'
  target: 'assets'
- source: 'i18n'
  target: 'i18n'
- source: 'archetypes'
  target: 'archetypes'
- source: 'partials'
  target: 'content'
